# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [11]:
# Create a 1-dimensional NumPy array using np.array()
one_array= np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
two_array= np.array([[1,2,3],[3,4,5]])

# Create a 3-dimensional Numpy array using np.array()
three_array= np.array([two_array,[[3,4,5],[4,5,6]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [12]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_array.ndim, one_array.shape, one_array.size, one_array.dtype

(1, (3,), 3, dtype('int32'))

In [13]:
# Attributes of 2-dimensional array
two_array.ndim, two_array.shape, two_array.size, two_array.dtype

(2, (2, 3), 6, dtype('int32'))

In [14]:
# Attributes of 3-dimensional array
three_array.ndim, three_array.shape, three_array.size, three_array.dtype

(3, (2, 2, 3), 12, dtype('int32'))

In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
arr1= pd.DataFrame(one_array)
arr1

0
0  1
1  2
2  3

In [25]:
# Create an array of shape (10, 2) with only ones
ones= np.ones((7,3,2))
ones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
print(np.zeros((7,2,3)))

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
# Create an array within a range of 0 and 100 with step 3
range_array= np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random1= np.random.randint(0,10,size=(7,2))
random1

array([[4, 1],
       [9, 3],
       [6, 2],
       [9, 1],
       [8, 6],
       [2, 1],
       [0, 9]])

In [37]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.seed(3)
random2= np.random.random((3,5))
(random2)

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]])

In [53]:
# Set the random seed to 42
np.random.seed(7)


# Create a random array of numbers between 0 & 10 of size (4, 6)
random3= np.random.randint(0,10,size=(4,6))
random3, random2

(array([[4, 9, 6, 3, 3, 7],
        [7, 9, 7, 8, 9, 8],
        [7, 6, 4, 0, 7, 0],
        [7, 6, 3, 5, 8, 8]]),
 array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
        [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
        [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]]))

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [68]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
var= np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
var, np.unique(var)

(array([[5, 9, 8, 1, 3, 8, 9],
        [9, 5, 1, 5, 2, 8, 5],
        [1, 2, 1, 7, 3, 1, 3]]),
 array([1, 2, 3, 5, 7, 8, 9]))

In [72]:
# Find the 0'th index of the latest array you created
var[0]

array([5, 9, 8, 1, 3, 8, 9])

In [73]:
# Get the first 2 rows of latest array you created
var[:2]

array([[5, 9, 8, 1, 3, 8, 9],
       [9, 5, 1, 5, 2, 8, 5]])

In [74]:
# Get the first 2 values of the first 2 rows of the latest array
var[:2,:2]

array([[5, 9],
       [9, 5]])

In [75]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
variable= np.random.randint(0,10, size=(3,5))
variable2= np.random.randint(0,10,size=(3,5))

In [76]:
# Add the two arrays together
variable+variable2

array([[11,  7,  9,  5,  6],
       [ 6,  5, 14, 15, 15],
       [11, 11,  7,  8, 13]])

In [77]:
# Create another array of ones of shape (5, 3)
variable3= np.random.random((5,3))

In [80]:
# Try add the array of ones and the other most recent array together
variable+variable3.reshape(3,5)

array([[4.39768066, 4.68238359, 1.42200153, 0.37128188, 0.53045266],
       [2.68424052, 3.11332567, 7.64520628, 6.18570533, 9.90768461],
       [3.748468  , 5.41861702, 6.56131823, 8.64661201, 6.77553491]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [83]:
# Create another array of ones of shape (3, 5)
variable4= np.random.randint(0,10,size=(3,5))

In [84]:
# Subtract the new array of ones from the other most recent array
variable-variable4

array([[ 0,  3, -8, -6, -5],
       [-4, -5,  2, -3,  5],
       [-3,  5,  0,  6,  3]])

In [87]:
# Multiply the ones array with the latest array
variable3.reshape(3,5)*variable

array([[1.59072266, 2.72953437, 0.42200153, 0.        , 0.        ],
       [1.36848104, 0.33997701, 4.51644399, 1.11423196, 8.16916147],
       [2.24540399, 2.09308508, 3.3679094 , 5.17289607, 4.65320949]])

In [88]:
# Take the latest array to the power of 2 using '**'
variable4, variable4**2

(array([[4, 1, 9, 6, 5],
        [6, 8, 5, 9, 4],
        [6, 0, 6, 2, 3]]),
 array([[16,  1, 81, 36, 25],
        [36, 64, 25, 81, 16],
        [36,  0, 36,  4,  9]]))

In [89]:
# Do the same thing with np.square()
np.square(variable4)

array([[16,  1, 81, 36, 25],
       [36, 64, 25, 81, 16],
       [36,  0, 36,  4,  9]])

In [90]:
# Find the mean of the latest array using np.mean()
np.mean(variable4)

4.933333333333334

In [91]:
# Find the maximum of the latest array using np.max()
np.max(variable4)

9

In [93]:
# Find the minimum of the latest array using np.min()
np.min(variable4)

0

In [94]:
# Find the standard deviation of the latest array
np.std(variable4)

2.594010194445829

In [95]:
# Find the variance of the latest array
np.var(variable4)

6.728888888888889

In [96]:
# Reshape the latest array to (3, 5, 1)
np.sqrt(np.var(variable4))

2.594010194445829

In [98]:
# Transpose the latest array
variable4.T.shape

(5, 3)

What does the transpose do?

In [101]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr= np.random.randint(0,10,size=(3,3))
arr2= np.random.randint(0,10,size=(3,3))

In [102]:
# Perform a dot product on the two newest arrays you created
np.dot(arr,arr2)

array([[84, 67, 63],
       [36, 28,  8],
       [81, 56, 11]])

In [103]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr= np.random.randint(0,10,size=(4,3))
arr2= np.random.randint(0,10,size=(4,3))

In [105]:
# Perform a dot product on the two newest arrays you created
np.dot(arr,arr2.T)

array([[121,  75, 114, 154],
       [ 44,  30,  45,  72],
       [117,  69, 111, 142],
       [ 71,  36,  75,  91]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [116]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr= np.random.randint(0,10,size=(3,3))
arr2= np.random.randint(0,10,size=(3,2))


In [107]:
# Compare the two arrays with '>'
arr>arr2

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='


In [108]:
# Find which elements of the first array are greater than 7
arr>7

array([[False, False,  True],
       [ True,  True, False],
       [False, False, False]])

In [109]:
# Which parts of each array are equal? (try using '==')
arr==arr2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [122]:
# Sort one of the arrays you just created in ascending order
arr2, np.sort(arr2), np.argsort(arr2)

(array([[7, 8],
        [3, 3],
        [0, 7]]),
 array([[7, 8],
        [3, 3],
        [0, 7]]),
 array([[0, 1],
        [0, 1],
        [0, 1]], dtype=int64))

In [44]:
# Sort the indexes of one of the arrays you just created


In [128]:
# Find the index with the maximum value in one of the arrays you've created
arr2, np.argmin(arr2, axis=0)

(array([[7, 8],
        [3, 3],
        [0, 7]]),
 array([2, 1], dtype=int64))

In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [135]:
# Create an array with 10 evenly spaced numbers between 1 and 100

arr_space= np.arange(9,100,10)
arr_space

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.